### ISSUE TITLE
V2 PCB to-do list

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/echo-chan#1]
- [ ] Amplify SYNC
- [ ] Add key to JAMMA edge
- [x] Remove unnecessary components (158b335d0dfda9c1f1c57ec360e20ba589522a71)
- [ ] Increase board width
